Fix missing EXPECTED_DOCKER_VERSION for release-repo
The release-repo pipeline expects this parameter to be set when
doing a release, and otherwise fails:

    ERROR: EXPECTED_DOCKER_VERSION is required when releasing Docker
    Finished: FAILURE

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>